name: Pull request checks

on: [pull_request]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run shellcheck
        run: |
          sudo apt install shellcheck
          shellcheck -S warning *.sh

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build docker image
        run: docker build -t ${{ github.repository_owner }}/rancher-cleanup:test .
